CREATE TABLE `employee_advances` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessId` int NOT NULL,
	`employeeId` int NOT NULL,
	`employeeName` varchar(100) NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`advanceDate` timestamp NOT NULL,
	`reason` text,
	`status` enum('pending','settled','cancelled') NOT NULL DEFAULT 'pending',
	`settledPeriodId` int,
	`expenseId` int,
	`createdBy` int NOT NULL,
	`createdByName` varchar(100) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_advances_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employee_salary_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessId` int NOT NULL,
	`employeeId` int NOT NULL,
	`salaryType` enum('monthly','daily','commission','mixed') NOT NULL,
	`baseSalary` decimal(10,2),
	`dailyRate` decimal(10,2),
	`commissionType` enum('per_order','percentage'),
	`commissionValue` decimal(10,2),
	`commissionBasis` enum('confirmed','prepared','shipped','delivered') NOT NULL DEFAULT 'delivered',
	`effectiveFrom` timestamp NOT NULL,
	`notes` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdByName` varchar(100) NOT NULL,
	`updatedBy` int,
	`updatedByName` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employee_salary_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `employee_salary_profiles_employee_effective_unique` UNIQUE(`employeeId`,`effectiveFrom`)
);
--> statement-breakpoint
CREATE TABLE `payroll_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`periodId` int NOT NULL,
	`businessId` int NOT NULL,
	`employeeId` int NOT NULL,
	`employeeName` varchar(100) NOT NULL,
	`salaryType` enum('monthly','daily','commission','mixed') NOT NULL,
	`salaryProfileId` int,
	`profileSnapshot` text,
	`baseSalary` decimal(10,2) NOT NULL DEFAULT '0',
	`attendanceDays` int NOT NULL DEFAULT 0,
	`absenceDays` int NOT NULL DEFAULT 0,
	`overtimeHours` decimal(6,2) NOT NULL DEFAULT '0',
	`overtimeAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`bonuses` decimal(10,2) NOT NULL DEFAULT '0',
	`commissions` decimal(10,2) NOT NULL DEFAULT '0',
	`commissionOrders` int NOT NULL DEFAULT 0,
	`absenceDeduction` decimal(10,2) NOT NULL DEFAULT '0',
	`deductions` decimal(10,2) NOT NULL DEFAULT '0',
	`advances` decimal(10,2) NOT NULL DEFAULT '0',
	`netSalary` decimal(10,2) NOT NULL DEFAULT '0',
	`manualFields` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_items_id` PRIMARY KEY(`id`),
	CONSTRAINT `payroll_items_period_employee_unique` UNIQUE(`periodId`,`employeeId`)
);
--> statement-breakpoint
CREATE TABLE `payroll_periods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessId` int NOT NULL,
	`year` int NOT NULL,
	`month` int NOT NULL,
	`status` enum('draft','approved','paid','cancelled') NOT NULL DEFAULT 'draft',
	`totalGross` decimal(12,2) NOT NULL DEFAULT '0',
	`totalNet` decimal(12,2) NOT NULL DEFAULT '0',
	`employeeCount` int NOT NULL DEFAULT 0,
	`expenseId` int,
	`notes` text,
	`createdBy` int NOT NULL,
	`createdByName` varchar(100) NOT NULL,
	`approvedBy` int,
	`approvedByName` varchar(100),
	`approvedAt` timestamp,
	`paidBy` int,
	`paidByName` varchar(100),
	`paidAt` timestamp,
	`cancelledBy` int,
	`cancelledByName` varchar(100),
	`cancelledAt` timestamp,
	`cancelReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_periods_id` PRIMARY KEY(`id`),
	CONSTRAINT `payroll_periods_business_period_unique` UNIQUE(`businessId`,`year`,`month`)
);
--> statement-breakpoint
CREATE TABLE `payroll_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`businessId` int NOT NULL,
	`workingDaysPerMonth` int NOT NULL DEFAULT 26,
	`absenceDeductionBasis` enum('calendar_days','working_days') NOT NULL DEFAULT 'working_days',
	`weekendDays` varchar(20) NOT NULL DEFAULT '5,6',
	`overtimeMode` enum('manual','hourly_multiplier') NOT NULL DEFAULT 'manual',
	`overtimeMultiplier` decimal(5,2) NOT NULL DEFAULT '1.50',
	`workHoursPerDay` decimal(4,2) NOT NULL DEFAULT '8.00',
	`currency` varchar(10) NOT NULL DEFAULT 'EGP',
	`roundingMode` enum('none','nearest_1','nearest_5','nearest_10') NOT NULL DEFAULT 'none',
	`defaultSalaryType` enum('monthly','daily','commission','mixed') NOT NULL DEFAULT 'monthly',
	`defaultCommissionBasis` enum('confirmed','prepared','shipped','delivered') NOT NULL DEFAULT 'delivered',
	`updatedBy` int,
	`updatedByName` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payroll_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `payroll_settings_business_unique` UNIQUE(`businessId`)
);
